### ISSUE TITLE
kitchen destroy not working

### ISSUE THREAD

**Issue by Steve-Griffin** [chef/knife-vcenter#16]
### Versions:

 gem --version
2.7.6

* Version of knife-vcenter:
1.4.2
* Version of chef:
Chef Workstation: 0.2.39
  chef-run: 0.2.4
  chef-client: 14.7.17
### Platform Details

* Version of vCenter:
6.7.0
build 11338799

### Scenario:

kitchen destroy only works on a successful kitchen test run. If test fails it will not destroy. if you run kitchen create,converge or verify kitchen destroy does not work.

### Actual Result:

 kitchen create
-----> Starting Kitchen (v1.23.2)
-----> Creating <default-windows2012r2>...
Cloning 'windows2012r2' to create the VM...
Waiting for network interfaces to become available...
       Finished creating <default-windows2012r2> (2m39.63s).
-----> Kitchen is finished. (3m4.08s)
PS C:\bsb\cookbooks\iis> kitchen destroy
-----> Starting Kitchen (v1.23.2)
-----> Destroying <default-windows2012r2>...
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: 1 actions failed.
>>>>>>     Failed to complete #destroy action: [] on default-windows2012r2
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
>>>>>> Also try running `kitchen diagnose --all` for configuration

PS C:\bsb\cookbooks\iis> cat .kitchen/logs/kitchen.log
I, [2019-01-21T11:30:09.162808 #10660]  INFO -- Kitchen: -----> Starting Kitchen (v1.23.2)
I, [2019-01-21T11:30:34.549533 #10660]  INFO -- Kitchen: -----> Destroying <default-windows2012r2>...
E, [2019-01-21T11:30:34.584234 #10660] ERROR -- Kitchen: ------Exception-------
E, [2019-01-21T11:30:34.586326 #10660] ERROR -- Kitchen: Class: Kitchen::ActionFailed
E, [2019-01-21T11:30:34.586628 #10660] ERROR -- Kitchen: Message: 1 actions failed.
>>>>>>     Failed to complete #destroy action: [] on default-windows2012r2
E, [2019-01-21T11:30:34.586909 #10660] ERROR -- Kitchen: ----------------------
E, [2019-01-21T11:30:34.587194 #10660] ERROR -- Kitchen: ------Backtrace-------
E, [2019-01-21T11:30:34.587460 #10660] ERROR -- Kitchen: C:/opscode/chef-workstation/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.23.2/lib/kitchen/command.rb:183:in `report_errors'
E, [2019-01-21T11:30:34.587717 #10660] ERROR -- Kitchen: C:/opscode/chef-workstation/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.23.2/lib/kitchen/command.rb:174:in `run_action'
E, [2019-01-21T11:30:34.587976 #10660] ERROR -- Kitchen: C:/opscode/chef-workstation/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.23.2/lib/kitchen/command/action.rb:36:in `block in call'
E, [2019-01-21T11:30:34.588227 #10660] ERROR -- Kitchen: C:/opscode/chef-workstation/embedded/lib/ruby/2.5.0/benchmark.rb:293:in `measure'
E, [2019-01-21T11:30:34.588517 #10660] ERROR -- Kitchen: C:/opscode/chef-workstation/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.23.2/lib/kitchen/command/action.rb:34:in `call'
E, [2019-01-21T11:30:34.588790 #10660] ERROR -- Kitchen: C:/opscode/chef-workstation/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.23.2/lib/kitchen/cli.rb:52:in `perform'
E, [2019-01-21T11:30:34.589017 #10660] ERROR -- Kitchen: C:/opscode/chef-workstation/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.23.2/lib/kitchen/cli.rb:193:in `block (2 levels) in <class:CLI>'
E, [2019-01-21T11:30:34.589598 #10660] ERROR -- Kitchen: C:/opscode/chef-workstation/embedded/lib/ruby/gems/2.5.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
E, [2019-01-21T11:30:34.590358 #10660] ERROR -- Kitchen: C:/opscode/chef-workstation/embedded/lib/ruby/gems/2.5.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
E, [2019-01-21T11:30:34.590684 #10660] ERROR -- Kitchen: C:/opscode/chef-workstation/embedded/lib/ruby/gems/2.5.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
E, [2019-01-21T11:30:34.590962 #10660] ERROR -- Kitchen: C:/opscode/chef-workstation/embedded/lib/ruby/gems/2.5.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
E, [2019-01-21T11:30:34.591239 #10660] ERROR -- Kitchen: C:/opscode/chef-workstation/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.23.2/bin/kitchen:13:in `block in <top (required)>'
E, [2019-01-21T11:30:34.591659 #10660] ERROR -- Kitchen: C:/opscode/chef-workstation/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.23.2/lib/kitchen/errors.rb:171:in `with_friendly_errors'
E, [2019-01-21T11:30:34.592426 #10660] ERROR -- Kitchen: C:/opscode/chef-workstation/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.23.2/bin/kitchen:13:in `<top (required)>'
E, [2019-01-21T11:30:34.592835 #10660] ERROR -- Kitchen: C:/opscode/chef-workstation/bin/kitchen:312:in `load'
E, [2019-01-21T11:30:34.593051 #10660] ERROR -- Kitchen: C:/opscode/chef-workstation/bin/kitchen:312:in `<main>'
E, [2019-01-21T11:30:34.593245 #10660] ERROR -- Kitchen: ----End Backtrace-----
E, [2019-01-21T11:30:34.593479 #10660] ERROR -- Kitchen: -Composite Exception--
E, [2019-01-21T11:30:34.593678 #10660] ERROR -- Kitchen: Class: Kitchen::ActionFailed
E, [2019-01-21T11:30:34.593858 #10660] ERROR -- Kitchen: Message: Failed to complete #destroy action: [] on default-windows2012r2
E, [2019-01-21T11:30:34.594037 #10660] ERROR -- Kitchen: ----------------------
E, [2019-01-21T11:30:34.594221 #10660] ERROR -- Kitchen: ------Backtrace-------
E, [2019-01-21T11:30:34.594418 #10660] ERROR -- Kitchen: C:/opscode/chef-workstation/embedded/lib/ruby/gems/2.5.0/gems/rbvmomi-1.13.0/lib/rbvmomi/vim.rb:32:in `connect'
E, [2019-01-21T11:30:34.594603 #10660] ERROR -- Kitchen: C:/Users/stephen.griffin/AppData/Local/chefdk/gem/ruby/2.5.0/gems/kitchen-vcenter-1.4.2/lib/kitchen/driver/vcenter.rb:263:in `lookup_service_host'
E, [2019-01-21T11:30:34.594840 #10660] ERROR -- Kitchen: C:/Users/stephen.griffin/AppData/Local/chefdk/gem/ruby/2.5.0/gems/kitchen-vcenter-1.4.2/lib/kitchen/driver/vcenter.rb:287:in `connect'
E, [2019-01-21T11:30:34.595037 #10660] ERROR -- Kitchen: C:/Users/stephen.griffin/AppData/Local/chefdk/gem/ruby/2.5.0/gems/kitchen-vcenter-1.4.2/lib/kitchen/driver/vcenter.rb:133:in `destroy'
E, [2019-01-21T11:30:34.595215 #10660] ERROR -- Kitchen: C:/opscode/chef-workstation/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.23.2/lib/kitchen/instance.rb:484:in `public_send'
E, [2019-01-21T11:30:34.595414 #10660] ERROR -- Kitchen: C:/opscode/chef-workstation/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.23.2/lib/kitchen/instance.rb:484:in `block in perform_action'
E, [2019-01-21T11:30:34.595595 #10660] ERROR -- Kitchen: C:/opscode/chef-workstation/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.23.2/lib/kitchen/instance.rb:551:in `synchronize_or_call'
E, [2019-01-21T11:30:34.595773 #10660] ERROR -- Kitchen: C:/opscode/chef-workstation/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.23.2/lib/kitchen/instance.rb:513:in `block in action'
E, [2019-01-21T11:30:34.595974 #10660] ERROR -- Kitchen: C:/opscode/chef-workstation/embedded/lib/ruby/2.5.0/benchmark.rb:293:in `measure'
E, [2019-01-21T11:30:34.596152 #10660] ERROR -- Kitchen: C:/opscode/chef-workstation/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.23.2/lib/kitchen/instance.rb:512:in `action'
E, [2019-01-21T11:30:34.596334 #10660] ERROR -- Kitchen: C:/opscode/chef-workstation/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.23.2/lib/kitchen/instance.rb:484:in `perform_action'
E, [2019-01-21T11:30:34.596603 #10660] ERROR -- Kitchen: C:/opscode/chef-workstation/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.23.2/lib/kitchen/instance.rb:471:in `destroy_action'
E, [2019-01-21T11:30:34.596859 #10660] ERROR -- Kitchen: C:/opscode/chef-workstation/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.23.2/lib/kitchen/instance.rb:382:in `block (2 levels) in transition_to'
E, [2019-01-21T11:30:34.597117 #10660] ERROR -- Kitchen: C:/opscode/chef-workstation/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.23.2/lib/kitchen/lifecycle_hooks.rb:45:in `run_with_hooks'
E, [2019-01-21T11:30:34.597385 #10660] ERROR -- Kitchen: C:/opscode/chef-workstation/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.23.2/lib/kitchen/instance.rb:381:in `block in transition_to'
E, [2019-01-21T11:30:34.597631 #10660] ERROR -- Kitchen: C:/opscode/chef-workstation/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.23.2/lib/kitchen/instance.rb:380:in `each'
E, [2019-01-21T11:30:34.597899 #10660] ERROR -- Kitchen: C:/opscode/chef-workstation/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.23.2/lib/kitchen/instance.rb:380:in `transition_to'
E, [2019-01-21T11:30:34.598169 #10660] ERROR -- Kitchen: C:/opscode/chef-workstation/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.23.2/lib/kitchen/instance.rb:173:in `destroy'
E, [2019-01-21T11:30:34.598431 #10660] ERROR -- Kitchen: C:/opscode/chef-workstation/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.23.2/lib/kitchen/command.rb:197:in `public_send'
E, [2019-01-21T11:30:34.598799 #10660] ERROR -- Kitchen: C:/opscode/chef-workstation/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.23.2/lib/kitchen/command.rb:197:in `run_action_in_thread'
E, [2019-01-21T11:30:34.599062 #10660] ERROR -- Kitchen: C:/opscode/chef-workstation/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.23.2/lib/kitchen/command.rb:169:in `block (2 levels) in run_action'
E, [2019-01-21T11:30:34.599386 #10660] ERROR -- Kitchen: C:/opscode/chef-workstation/embedded/lib/ruby/gems/2.5.0/gems/logging-2.2.2/lib/logging/diagnostic_context.rb:474:in `block in create_with_logging_context'
E, [2019-01-21T11:30:34.599638 #10660] ERROR -- Kitchen: ----End Backtrace-----
E, [2019-01-21T11:30:34.599888 #10660] ERROR -- Kitchen: ---Nested Exception---
E, [2019-01-21T11:30:34.600150 #10660] ERROR -- Kitchen: Class: Kitchen::ActionFailed
E, [2019-01-21T11:30:34.600422 #10660] ERROR -- Kitchen: Message: Failed to complete #destroy action: []
E, [2019-01-21T11:30:34.600665 #10660] ERROR -- Kitchen: ----------------------
E, [2019-01-21T11:30:34.600913 #10660] ERROR -- Kitchen: ------Backtrace-------
E, [2019-01-21T11:30:34.601164 #10660] ERROR -- Kitchen: C:/opscode/chef-workstation/embedded/lib/ruby/gems/2.5.0/gems/rbvmomi-1.13.0/lib/rbvmomi/vim.rb:32:in `connect'
E, [2019-01-21T11:30:34.601433 #10660] ERROR -- Kitchen: C:/Users/stephen.griffin/AppData/Local/chefdk/gem/ruby/2.5.0/gems/kitchen-vcenter-1.4.2/lib/kitchen/driver/vcenter.rb:263:in `lookup_service_host'
E, [2019-01-21T11:30:34.601680 #10660] ERROR -- Kitchen: C:/Users/stephen.griffin/AppData/Local/chefdk/gem/ruby/2.5.0/gems/kitchen-vcenter-1.4.2/lib/kitchen/driver/vcenter.rb:287:in `connect'
E, [2019-01-21T11:30:34.601937 #10660] ERROR -- Kitchen: C:/Users/stephen.griffin/AppData/Local/chefdk/gem/ruby/2.5.0/gems/kitchen-vcenter-1.4.2/lib/kitchen/driver/vcenter.rb:133:in `destroy'
E, [2019-01-21T11:30:34.602188 #10660] ERROR -- Kitchen: C:/opscode/chef-workstation/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.23.2/lib/kitchen/instance.rb:484:in `public_send'
E, [2019-01-21T11:30:34.602446 #10660] ERROR -- Kitchen: C:/opscode/chef-workstation/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.23.2/lib/kitchen/instance.rb:484:in `block in perform_action'
E, [2019-01-21T11:30:34.602695 #10660] ERROR -- Kitchen: C:/opscode/chef-workstation/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.23.2/lib/kitchen/instance.rb:551:in `synchronize_or_call'
E, [2019-01-21T11:30:34.602952 #10660] ERROR -- Kitchen: C:/opscode/chef-workstation/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.23.2/lib/kitchen/instance.rb:513:in `block in action'
E, [2019-01-21T11:30:34.603209 #10660] ERROR -- Kitchen: C:/opscode/chef-workstation/embedded/lib/ruby/2.5.0/benchmark.rb:293:in `measure'
E, [2019-01-21T11:30:34.603708 #10660] ERROR -- Kitchen: C:/opscode/chef-workstation/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.23.2/lib/kitchen/instance.rb:512:in `action'
E, [2019-01-21T11:30:34.603990 #10660] ERROR -- Kitchen: C:/opscode/chef-workstation/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.23.2/lib/kitchen/instance.rb:484:in `perform_action'
E, [2019-01-21T11:30:34.604285 #10660] ERROR -- Kitchen: C:/opscode/chef-workstation/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.23.2/lib/kitchen/instance.rb:471:in `destroy_action'
E, [2019-01-21T11:30:34.604579 #10660] ERROR -- Kitchen: C:/opscode/chef-workstation/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.23.2/lib/kitchen/instance.rb:382:in `block (2 levels) in transition_to'
E, [2019-01-21T11:30:34.604859 #10660] ERROR -- Kitchen: C:/opscode/chef-workstation/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.23.2/lib/kitchen/lifecycle_hooks.rb:45:in `run_with_hooks'
E, [2019-01-21T11:30:34.605125 #10660] ERROR -- Kitchen: C:/opscode/chef-workstation/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.23.2/lib/kitchen/instance.rb:381:in `block in transition_to'
E, [2019-01-21T11:30:34.605393 #10660] ERROR -- Kitchen: C:/opscode/chef-workstation/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.23.2/lib/kitchen/instance.rb:380:in `each'
E, [2019-01-21T11:30:34.605617 #10660] ERROR -- Kitchen: C:/opscode/chef-workstation/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.23.2/lib/kitchen/instance.rb:380:in `transition_to'
E, [2019-01-21T11:30:34.605881 #10660] ERROR -- Kitchen: C:/opscode/chef-workstation/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.23.2/lib/kitchen/instance.rb:173:in `destroy'
E, [2019-01-21T11:30:34.606288 #10660] ERROR -- Kitchen: C:/opscode/chef-workstation/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.23.2/lib/kitchen/command.rb:197:in `public_send'
E, [2019-01-21T11:30:34.606828 #10660] ERROR -- Kitchen: C:/opscode/chef-workstation/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.23.2/lib/kitchen/command.rb:197:in `run_action_in_thread'
E, [2019-01-21T11:30:34.607262 #10660] ERROR -- Kitchen: C:/opscode/chef-workstation/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.23.2/lib/kitchen/command.rb:169:in `block (2 levels) in run_action'
E, [2019-01-21T11:30:34.607725 #10660] ERROR -- Kitchen: C:/opscode/chef-workstation/embedded/lib/ruby/gems/2.5.0/gems/logging-2.2.2/lib/logging/diagnostic_context.rb:474:in `block in create_with_logging_context'
E, [2019-01-21T11:30:34.608129 #10660] ERROR -- Kitchen: ----End Backtrace-----
PS C:\bsb\cookbooks\iis>

**Comment by nimDevOps** [comment]
Same issue is happening to me for last few months, do not remember how long as I use destroy rarely;
I use kitchen-vcenter driver.
Most likely this is not knife-vcenter nor kitchen-vcenter but somewhere in common gems.

$ chef --version
Chef Development Kit Version: 3.11.3
chef-client version: 14.13.11
delivery version: master (9d07501a3b347cc687c902319d23dc32dd5fa621)
berks version: 7.0.8
kitchen version: 1.25.0
inspec version: 3.9.3


$ kitchen destroy --log-level=DEBUG Docker-Photon2
-----> Starting Kitchen (v1.25.0)
-----> Destroying <Docker-Photon2>...
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: 1 actions failed.
>>>>>>     Failed to complete #destroy action: [] on Docker-Photon2
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
>>>>>> Also try running `kitchen diagnose --all` for configuration
D      ------Exception-------
D      Class: Kitchen::ActionFailed
D      Message: 1 actions failed.
>>>>>>     Failed to complete #destroy action: [] on Docker-Photon2
D      ----------------------
D      ------Backtrace-------
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.25.0/lib/kitchen/command.rb:184:in `report_errors'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.25.0/lib/kitchen/command.rb:175:in `run_action'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.25.0/lib/kitchen/command/action.rb:36:in `block in call'
D      C:/opscode/chefdk/embedded/lib/ruby/2.5.0/benchmark.rb:293:in `measure'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.25.0/lib/kitchen/command/action.rb:34:in `call'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.25.0/lib/kitchen/cli.rb:52:in `perform'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.25.0/lib/kitchen/cli.rb:198:in `block (2 levels) in <class:CLI>'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.5.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.5.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.5.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.5.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.25.0/bin/kitchen:13:in `block in <top (required)>'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.25.0/lib/kitchen/errors.rb:171:in `with_friendly_errors'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.25.0/bin/kitchen:13:in `<top (required)>'
D      C:/opscode/chefdk/embedded/bin/kitchen:23:in `load'
D      C:/opscode/chefdk/embedded/bin/kitchen:23:in `<main>'
D      ----End Backtrace-----
D      -Composite Exception--
D      Class: Kitchen::ActionFailed
D      Message: Failed to complete #destroy action: [] on Docker-Photon2
D      ----------------------
D      ------Backtrace-------
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.5.0/gems/rbvmomi-1.13.0/lib/rbvmomi/vim.rb:32:in `connect'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.5.0/gems/kitchen-vcenter-1.4.2/lib/kitchen/driver/vcenter.rb:263:in `lookup_service_host'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.5.0/gems/kitchen-vcenter-1.4.2/lib/kitchen/driver/vcenter.rb:287:in `connect'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.5.0/gems/kitchen-vcenter-1.4.2/lib/kitchen/driver/vcenter.rb:133:in `destroy'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.25.0/lib/kitchen/instance.rb:485:in `public_send'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.25.0/lib/kitchen/instance.rb:485:in `block in perform_action'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.25.0/lib/kitchen/instance.rb:552:in `synchronize_or_call'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.25.0/lib/kitchen/instance.rb:514:in `block in action'
D      C:/opscode/chefdk/embedded/lib/ruby/2.5.0/benchmark.rb:293:in `measure'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.25.0/lib/kitchen/instance.rb:513:in `action'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.25.0/lib/kitchen/instance.rb:485:in `perform_action'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.25.0/lib/kitchen/instance.rb:472:in `destroy_action'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.25.0/lib/kitchen/instance.rb:382:in `block (2 levels) in transition_to'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.25.0/lib/kitchen/lifecycle_hooks.rb:45:in `run_with_hooks'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.25.0/lib/kitchen/instance.rb:381:in `block in transition_to'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.25.0/lib/kitchen/instance.rb:380:in `each'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.25.0/lib/kitchen/instance.rb:380:in `transition_to'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.25.0/lib/kitchen/instance.rb:173:in `destroy'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.25.0/lib/kitchen/command.rb:198:in `public_send'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.25.0/lib/kitchen/command.rb:198:in `run_action_in_thread'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.25.0/lib/kitchen/command.rb:169:in `block (2 levels) in run_action'
D      ----End Backtrace-----
D      ---Nested Exception---
D      Class: Kitchen::ActionFailed
D      Message: Failed to complete #destroy action: []
D      ----------------------
D      ------Backtrace-------
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.5.0/gems/rbvmomi-1.13.0/lib/rbvmomi/vim.rb:32:in `connect'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.5.0/gems/kitchen-vcenter-1.4.2/lib/kitchen/driver/vcenter.rb:263:in `lookup_service_host'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.5.0/gems/kitchen-vcenter-1.4.2/lib/kitchen/driver/vcenter.rb:287:in `connect'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.5.0/gems/kitchen-vcenter-1.4.2/lib/kitchen/driver/vcenter.rb:133:in `destroy'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.25.0/lib/kitchen/instance.rb:485:in `public_send'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.25.0/lib/kitchen/instance.rb:485:in `block in perform_action'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.25.0/lib/kitchen/instance.rb:552:in `synchronize_or_call'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.25.0/lib/kitchen/instance.rb:514:in `block in action'
D      C:/opscode/chefdk/embedded/lib/ruby/2.5.0/benchmark.rb:293:in `measure'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.25.0/lib/kitchen/instance.rb:513:in `action'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.25.0/lib/kitchen/instance.rb:485:in `perform_action'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.25.0/lib/kitchen/instance.rb:472:in `destroy_action'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.25.0/lib/kitchen/instance.rb:382:in `block (2 levels) in transition_to'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.25.0/lib/kitchen/lifecycle_hooks.rb:45:in `run_with_hooks'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.25.0/lib/kitchen/instance.rb:381:in `block in transition_to'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.25.0/lib/kitchen/instance.rb:380:in `each'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.25.0/lib/kitchen/instance.rb:380:in `transition_to'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.25.0/lib/kitchen/instance.rb:173:in `destroy'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.25.0/lib/kitchen/command.rb:198:in `public_send'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.25.0/lib/kitchen/command.rb:198:in `run_action_in_thread'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.25.0/lib/kitchen/command.rb:169:in `block (2 levels) in run_action'
D      ----End Backtrace-----
