### ISSUE TITLE
Convert this knife plugin to use the new 

### ISSUE THREAD

**Issue by tas50** [chef/knife-vcenter#17]
VMware has entirely rewritten their API gem and pushed it to Rubygems. That means that this knife plugin no longer works. It also means we have the ability to finally package this knife tool in DK.

Here's the gem https://rubygems.org/gems/vsphere-automation-sdk

Here's the same work that we did with the kitchen-vcenter driver https://github.com/chef/kitchen-vcenter/pull/55

**Comment by tecracer-theinen** [comment]
I guess I'll take a look :) The code base seems nearly identical in some parts anyway.

**Comment by tecracer-theinen** [comment]
As I see no reviewers assigned in this project, I am sorry to ping you @tas50 - but it seems necessary ;)
