### ISSUE TITLE
"Clone" operation does not work

### ISSUE THREAD

**Issue by tecracer-theinen** [chef/knife-vcenter#19]
### Versions:
* Version of knife-vcenter: 2.0.2
* Version of chef: 14.10.9

### Platform Details
* Version of vCenter: 6.7.0
* Version of ESXi: 6.7.0

### Scenario:
Trying to run a clone operation fails due to `undefined method get_resource_pool`

### Steps to Reproduce:
Install knife-vcenter in version 2.0.2 and run `knife vcenter vm clone NAME`

### Expected Result:
Cloning of the VM

### Actual Result:
```
C:/Users/XXXXXXXX/.chefdk/gem/ruby/2.5.0/gems/knife-vcenter-2.0.2/lib/chef/knife/cloud/vcenter_service.rb:91:in `create_server': undefined method `get_resource_pool' for #<Chef::Knife::Cloud::VcenterService:0x0000000009dc9098> (NoMethodError)
Did you mean?  get_resourcepool
        from C:/opscode/chefdk/embedded/lib/ruby/gems/2.5.0/gems/knife-cloud-1.2.3/lib/chef/knife/cloud/server/create_command.rb:66:in `execute_command'
        from C:/opscode/chefdk/embedded/lib/ruby/gems/2.5.0/gems/knife-cloud-1.2.3/lib/chef/knife/cloud/command.rb:50:in `run'
        from C:/opscode/chefdk/embedded/lib/ruby/gems/2.5.0/gems/chef-14.10.9-universal-mingw32/lib/chef/knife.rb:446:in `block in run_with_pretty_exceptions'
        from C:/opscode/chefdk/embedded/lib/ruby/gems/2.5.0/gems/chef-14.10.9-universal-mingw32/lib/chef/local_mode.rb:44:in `with_server_connectivity'
        from C:/opscode/chefdk/embedded/lib/ruby/gems/2.5.0/gems/chef-14.10.9-universal-mingw32/lib/chef/knife.rb:445:in `run_with_pretty_exceptions'
        from C:/opscode/chefdk/embedded/lib/ruby/gems/2.5.0/gems/chef-14.10.9-universal-mingw32/lib/chef/knife.rb:220:in `run'
        from C:/opscode/chefdk/embedded/lib/ruby/gems/2.5.0/gems/chef-14.10.9-universal-mingw32/lib/chef/application/knife.rb:161:in `run'
        from C:/opscode/chefdk/embedded/lib/ruby/gems/2.5.0/gems/chef-14.10.9-universal-mingw32/bin/knife:24:in `<top (required)>'
        from C:/opscode/chefdk/bin/knife:322:in `load'
        from C:/opscode/chefdk/bin/knife:322:in `<main>'
```

Thanks to Kevin Sample for bringing this up on Slack!

**Comment by tecracer-theinen** [comment]
This is due to me messing up something on the commit/PR and a trivial fix. I am currently testing that the error has really been removed. Will create a PR shortly, when everything works.

Opening this issue mainly for future reference, when somebody tries cloning with this version

**Comment by dmitri-s** [comment]
Hello @tecracer-theinen,
I am getting the following error:
`Exception: NoMethodError: undefined method `find_vm' for nil:NilClass`

I cloned your repo `git clone https://github.com/tecracer-theinen/knife-vcenter.git`
Checked out fix/issue-19 branch `git checkout fix/issue-19`
Built `chef gem build ./knife-vcenter.gemspec`
Installed `chef gem install knife-vcenter-2.0.2.gem`
